---
title: "Naive_Bayes"
author: "Irving, Chuy"
date: "2025-03-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(readr)
library(caret)
library(e1071)
library(dplyr)
```

A continuacion se construye un modelo de regresion lineal utilizando Naive Bayes.
```{r load_data, include=FALSE}
train_data <- read_csv("train_final.csv")
test_data <- read.csv("test_final.csv")
```

Eliminamos las columnas que tambien se removieron en el otro modelo, dado que causaban problemas y no eran relevantes.

```{r remove_columns, echo=FALSE}
train_data <- train_data %>% select(-Condition2, -RoofMatl, -Exterior2nd, -Electrical)
test_data <- test_data %>% select(-Condition2, -RoofMatl, -Exterior2nd, -Electrical)
```


```{r discretize, echo=FALSE}
# Discretizar 'SalePrice' en el conjunto de entrenamiento
train_data$SalePriceCat <- cut(train_data$SalePrice,
                               breaks = c(min(train_data$SalePrice),
                                          quantile(train_data$SalePrice, probs = 1/3),
                                          quantile(train_data$SalePrice, probs = 2/3),
                                          max(train_data$SalePrice)),
                               labels = c("barata", "estandar", "cara"),
                               include.lowest = TRUE)

# Discretizar 'SalePrice' en el conjunto de prueba
test_data$SalePriceCat <- cut(test_data$SalePrice, 
                              breaks = c(min(train_data$SalePrice), 
                                         quantile(train_data$SalePrice, probs = 1/3), 
                                         quantile(train_data$SalePrice, probs = 2/3),
                                         max(train_data$SalePrice)),
                              labels = c("barata", "estandar", "cara"),
                              include.lowest = TRUE)


```

```{r cut_points}
cut_points <- quantile(train_data$SalePrice, probs = c(0, 1/3, 2/3, 1))
print(puntos_de_corte)
table(train_data$SalePriceCat)
```

```{r naive_model, echo=FALSE}

modelo <- naiveBayes(SalePriceCat ~ ., data = train_data)

```

```{r predictions_test, echo=FALSE}
predictions <- predict(modelo, newdata = test_data, type = "class")

cmatrix <- confusionMatrix(predictions, test_data$SalePriceCat)
print(cmatrix)

```